[colors]
    draw_bold_text_with_bright_colors = true

    [colors.bright]
        black   = "#625e4c"
        blue    = "#9d65ff"
        cyan    = "#58d1eb"
        green   = "#98e024"
        magenta = "#f4005f"
        red     = "#f4005f"
        white   = "#f6f6ef"
        yellow  = "#e0d561"

    [colors.normal]
        black   = "#1a1a1a"
        blue    = "#9d65ff"
        cyan    = "#58d1eb"
        green   = "#98e024"
        magenta = "#f4005f"
        red     = "#f4005f"
        white   = "#c4c5b5"
        yellow  = "#fa8419"

    [colors.primary]
        background = "#21232b"
        foreground = "#dddddd"


    [colors.selection]
        background = "#ffb07c"
        text = "#21232b"

    [cursor.style]
        blinking = "off"
        shape = "Beam"

    [font]
        size = 12

    [font.bold]
        family = "FiraCode Nerd Font"
        style = "Bold"

    [font.glyph_offset]
        x = 0
        y = 0

    [font.italic]
        family = "FiraCode Nerd Font"
        style = "Italic"

    [font.normal]
        family = "FiraCode Nerd Font"
        style = "Regular"

    [font.offset]
        x = 0
        y = 0

    [[keyboard.bindings]]
        action = "SpawnNewInstance"
        key = "N"
        mods = "Control"

    [scrolling]
        history = 10000
        multiplier = 3

    [window]
        opacity = 0.99

    [window.dimensions]
        columns = 115
        lines = 34

    [window.padding]
        x = 35
        y = 35